insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('056674574465','参数设置','Sys/sys_Param.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('294523963000','快捷方式管理','Sys/shortcut_list.aspx',1,1,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('410220205600','创建功能菜单','sys/Navimenu.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('413290500173','配置文件','sys/const.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('851773403165','数据库维护','Sys/database.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('442546686430','模板管理','Templet/Manage_List.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('847520049417','菜单管理','sys/Navimenu_list.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('495088037032','添加栏目','news/Class_add.aspx?SiteID=',1,10,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('073624005253','创建日历','../user/info/Logs.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('294523963000','快捷方式管理','info/shortcut_list.aspx',0,1,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('977570576433','修改密码','info/user_ChangePassword.aspx',0,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('422695133884','我的资料','info/userinfo.aspx',0,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('049651556270','修改基本信息','info/userinfo_update.aspx',0,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('887598701704','添加帮助','../help/helpadd.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('471289082175','友情连接','info/friend.aspx',0,2,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('676478999506','广告','info/applyads.aspx',0,6,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('197809026776','<font color=red>回收站</font>','news/recyle.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('021703692356','<font color=blue><b>添加新闻</b></font>','news/news_add.aspx',1,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('676478999505','网址收藏夹','info/url.aspx',0,0,'0','0');
insert into [fs_api_qmenu] ([QmID],[qName],[FilePath],[Ismanage],[OrderID],[usernum],[siteID]) values ('689951000027','发表文章','/user/constr/constr.aspx',0,0,'759669605652','0');